---
title: "Baseball Exploratory"
author: "Matthew Johns"
date: "4/21/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
```

```{r necessities}

source("libraries.R")
source("queries.R")
#here::here()

```

```{r data-ingest}

con <- dbConnect(RSQLite::SQLite(), here::here("background-files/lahmansbaseballdb.sqlite"))

teams <- dbGetQuery(con, q_teams)

salaries <- dbGetQuery(con, q_salaries)

postseason <- dbGetQuery(con, q_postseason)

#head(postseason)


dbDisconnect(con)

```



```{r salaries-prep}

# count(salaries, salary, sort = FALSE)   # Values below $60,000 are outliers

salaries <- salaries %>% filter(salary >= 60000)

```


```{r team-payroll}

payroll_team <- salaries %>% group_by(teamID, yearID) %>% summarise(payroll_team = sum(salary)/1000000)   # in millions

payroll_team %<>% left_join(teams, by = c("yearID","teamID"))                                             # adds the teams columns

payroll_team %<>% mutate(WSWin = factor(WSWin)                                                            # typing to factor
                              ,yearID = factor(yearID))


# payroll grouped by year

payroll_year <- payroll_team %>% group_by(yearID) %>% summarise(mean_payroll_year = mean(payroll_team)
                                                                , sd_payroll_year = sqrt(var(payroll_team))
                                                                , cv_payroll_year = sd_payroll_year / mean_payroll_year)   


# team payroll adjusted by yearly mean

payroll_team %<>% left_join(payroll_year) %>% mutate(payroll_team_mean_adj = payroll_team / mean_payroll_year)   



```




```{r plots}

ggplot(payroll_team, aes(yearID, payroll_team)) + 
  geom_boxplot() + 
  theme(axis.text.x = element_text(vjust = 0.5, hjust = 1, angle = 90)) + 
  labs(title = "Payroll by Team and Year")


ggplot(payroll_team, aes(yearID, payroll_team_mean_adj)) + 
  geom_boxplot() + 
  theme(axis.text.x = element_text(vjust = 0.5, hjust = 1, angle = 90)) + 
  labs(title = "Mean-Adjusted Payroll by Team and Year")


ggplot(payroll_year, aes(yearID, cv_payroll_year)) + 
  geom_point() + 
  theme(axis.text.x = element_text(vjust = 0.5, hjust = 1, angle = 90)) + 
  labs(title = "Coefficient of Variation by Year")

```






















